### ISSUE TITLE
Build.PL double-dash parameters

### ISSUE THREAD

**Issue by sezal** [maxmind/MaxMind-DB-Reader-XS#10]
Prior to 1.000001 Build.PL used to accept parameters with double-dash (--), but such parameters not recognized anymore and the module fails to install (on Ubuntu at least).

This is how we build the module:

``` bash
$ ./Build.PL --installdirs site --extra_compiler_flags='...' --extra_linker_flags='...'
Unknown option: installdirs
Unknown option: extra_compiler_flags
Unknown option: extra_linker_flags
Too early to specify a build action 'site'.  Do 'Build site' instead.
```

We can pass, extra_compiler_flags/extra_linker_flags without dashes, but `--installdirs site` portion is appended by CPAN itself and may vary by OS. This is what Ubuntu has:

``` bash
$ grep mbuildpl_arg ~/.cpan/CPAN/MyConfig.pm
  'mbuildpl_arg' => q[--installdirs site],
```

It seems like Build.PL need to be fixed to accept double-dash parameters.

**Comment by inebritov** [comment]
I have the same problem with 1.000003 version. Solved by installation using cpanm:
```
cpan App::cpanminus
cpanm MaxMind::DB::Reader::XS
```

**Comment by oschwald** [comment]
Is this still an issue for you?

**Comment by sezal** [comment]
Unfortunately I don't have Ubuntu to test this.

**Comment by oschwald** [comment]
Given that this module is deprecated and this isn't a major bug or security issue, I am going to go ahead and close this.
