### ISSUE TITLE
Reader-broken-database.t fails one test (Debian)

### ISSUE THREAD

**Issue by version-free** [maxmind/MaxMind-DB-Reader-XS#11]
Installation of the module fails one test (running cpanm on Debian, libmaxminddb 1.1.4 installed from https://github.com/maxmind/libmaxminddb/releases).

Failed test 'expected exception with unknown file type' at t/MaxMind/DB/Reader-broken-databases.t line 76.
'MaxMind::DB::Reader::XS - Error opening database file "/tmp/FTtnzaB3pm/garbage": The MaxMind DB file contains invalid metadata at /home/[removed]/.cpanm/work/1/MaxMind-DB-Reader-XS-1.000001/blib/lib/MaxMind/DB/Reader/XS.pm line 68.'
doesn't match '(?^:Error opening database file "\/tmp\/FTtnzaB3pm\/garbage": The lookup path does not match the data .+)'
Looks like you failed 1 test of 5.

**Comment by autarch** [comment]
Thanks for the report, a new release should be out shortly to fix this.

**Comment by autarch** [comment]
I just uploaded a release to CPAN that should fix this.
