### ISSUE TITLE
XS reader is broken with the latest libmaxminddb

### ISSUE THREAD

**Issue by autarch** [maxmind/MaxMind-DB-Reader-XS#12]
The XS reader calculates and sets offsets that it passes to libmaxminddb. This depends on private behavior of libmaxminddb and it broke with the latest release.

See https://github.com/maxmind/libmaxminddb/issues/110 for the description of the change we want to make to libmaxminddb

A/C:
* Use new libmaxminddb `MMDB_read_node` functionality
* Will only install if libmaxminddb supports new functionality

**Comment by oschwald** [comment]
My thoughts on this are that we should move `_iterate_search_tree` out of the code shared by the XS and PP reader and have separate implementations for both. It might be easiest to do the XS one completely in XS rather than Perl.

**Comment by autarch** [comment]
I think having separate implementations makes sense. Doing it entirely in XS is up to you. Calling back into Perl from XS is tedious, but reasonable well-documented. Just make sure to use all the relevant stack macros (`SPAGAIN`, `PUTBACK`, etc.).
