### ISSUE TITLE
Weird Travis failures

### ISSUE THREAD

**Issue by autarch** [maxmind/MaxMind-DB-Reader-XS#15]
There are multiple dependency issues and bizarre failures. For instance, Net::Works is failing to install.

https://travis-ci.org/maxmind/MaxMind-DB-Reader-XS/builds/102476130

Greg says "I did look into them. Net::Works is failing to build for some, and the metadata object is getting created incorrectly on the Perl, not XS side for others. For the metadata ones, the correct hash is being passed to the MaxMind::DB::Metadata constructor but the object isn't getting constructed properly. See the debugging output from:"

https://travis-ci.org/maxmind/MaxMind-DB-Reader-XS/jobs/118084574#L873

**Comment by oschwald** [comment]
Closing due to age and the fact that we haven't seen this since.
