### ISSUE TITLE
problem installing on macOS Mojave

### ISSUE THREAD

**Issue by thvv** [maxmind/MaxMind-DB-Reader-XS#28]
Installing MaxMind::DB::Reader::XS from cpan on Mojave
halts with the message that maxminddb_config.h is not provided.
It's right there next to maxminddb.h.

**Comment by oschwald** [comment]
What error do you get?

**Comment by thvv** [comment]
(sorry, hit return instead of tab, updated comment)

**Comment by gpacuilla** [comment]
@thvv 

Hello,
The header files (*.h) need to be located within an include path for the compiler (see below)
If you installed `libmaxminddb` via homebrew, it would automatically link to `/usr/local/include` and work as expected (I just tested installing this via cpan on my Mojave 10.14.2)

```$  echo | cc -E -Wp,-v -
clang -cc1 version 10.0.0 (clang-1000.10.44.4) default target x86_64-apple-darwin18.2.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks (framework directory)
End of search list.```

**Comment by thvv** [comment]
Thanks for the pointer.  I was not using homebrew. 
maxminddb_config.h is in /usr/local/include though.
I think the issue is that Build.PL is looking in a different place to make sure it is there,
and outputting the message 
  It looks like the version of libmaxminddb that you installed did not provide a
  maxminddb_config.h header. Please upgrade your libmaxminddb installation.

**Comment by thvv** [comment]
I did your "echo" line and got essentially the same result. /usr/local/include was first.

**Comment by gpacuilla** [comment]
Does this also show /usr/local/include like mine?

```
$  perl -V | grep -i ccflags
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.14 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV'
```

**Comment by thvv** [comment]
no, doesn't.  is there an "o conf" I can use to set it?

    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.14 -pipe -Os -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -fno-strict-aliasing -fstack-protector-strong -I/opt/local/include -DPERL_USE_SAFE_PUTENV'

**Comment by thvv** [comment]
what if i copy the libmaxminddb includes to /opt/local/include?

**Comment by thvv** [comment]
yup, that did it.  thanks for the clue!

**Comment by gpacuilla** [comment]
Great! Glad to help. I would recommend looking into homebrew and perlbrew, both of which I use, might make your life much easier in the long term.
