### ISSUE TITLE
Reader stops working until service is restarted

### ISSUE THREAD

**Issue by robrwo** [maxmind/MaxMind-DB-Reader-XS#29]
After running for a while (hours, days, maybe weeks) we start getting these errors, where the reader stops working:

> MaxMind::DB::Reader::XS - error decoding unknown type number 222 at [deleted]/lib/perl5/x86_64-linux/MaxMind/DB/Reader/XS.pm line 56

Sometimes we also get errors like

> MaxMind::DB::Reader::XS - Entry data error looking up "106.197.196.58": The MaxMind DB file's data section contains bad data (unknown data type or corrupt data) at  [deleted]/lib/perl5/x86_64-linux/MaxMind/DB/Reader/XS.pm line 56

Restarting the service fixes the issue.

**Comment by oschwald** [comment]
Did the errors start after you deployed a new database?

**Comment by robrwo** [comment]
Hm, yes, I think that is the cause of the issue.
